2023-07-06 08:59:57.504207
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-08 08:58:14.485244
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-09 09:02:13.023131
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-10 08:58:23.218663
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-02 08:46:51.280175
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-03 08:46:40.990733
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-04 08:46:54.274172
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-05 08:44:52.829113
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-06 08:42:20.410089
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-07 08:46:32.046625
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-08 08:45:23.248673
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-09 08:46:39.916692
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-12 08:36:32.143485
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-13 08:39:44.913390
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-14 08:38:32.448424
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-15 08:37:43.847400
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-16 08:37:49.084060
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-17 08:37:03.422668
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-18 08:37:31.631737
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-19 08:36:02.741304
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-20 08:39:43.850477
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-08-21 08:38:08.362494
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-08-22 08:38:30.066168
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-23 08:37:47.608576
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-24 08:37:41.396510
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-25 08:38:34.700677
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-26 08:36:59.899399
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-27 08:40:41.236712
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-28 08:39:16.329676
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-29 08:38:46.764454
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-08-31 08:38:57.951624
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-01 08:41:37.734541
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-02 08:37:11.698706
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-03 08:41:01.852636
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-04 08:39:44.447683
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-05 08:38:10.814144
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-06 08:38:50.207669
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-07 08:38:17.834586
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-08 08:38:31.353891
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-09 08:37:46.696093
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-10 08:41:16.371111
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-11 08:39:26.805152
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-12 08:37:46.484138
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-13 08:39:11.394596
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-14 08:38:46.127441
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-15 08:39:21.237719
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-16 08:38:11.961455
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-17 08:41:48.727050
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-18 08:39:34.306467
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-19 08:39:37.314899
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-20 08:39:11.809180
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-21 08:39:19.092392
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-22 08:39:29.570126
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-23 08:37:57.245887
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-24 08:41:39.579797
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-25 08:39:54.427485
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-09-26 08:39:54.234786
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-27 08:40:01.876231
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-28 08:39:30.011864
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-09-29 08:39:42.664699
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-09-30 08:38:30.951837
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-01 08:45:17.561806
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-02 08:40:08.341269
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-03 08:40:11.545031
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-04 08:40:16.933262
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-05 08:39:43.483671
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-06 08:39:40.424601
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-07 08:39:17.513421
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-08 08:42:48.771881
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-09 08:40:00.012192
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-10 08:39:31.913808
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-11 08:39:33.430350
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-12 08:38:01.858798
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-13 08:40:46.773198
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-14 08:38:36.396117
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-15 08:42:59.724219
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-16 08:40:56.845462
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-17 08:40:04.065750
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-18 08:39:57.177593
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-19 08:39:43.235859
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-20 08:39:43.811465
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-21 08:38:28.130683
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-22 08:42:46.660138
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-23 08:40:14.560597
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-24 08:39:51.402049
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-25 08:39:45.994300
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-26 08:38:49.420961
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-27 08:39:07.851293
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-28 08:38:23.753152
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-29 08:42:37.101945
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-30 08:40:36.318455
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-31 08:40:15.085353
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-01 08:42:36.967126
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-11-02 08:39:51.715111
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-03 08:40:10.096073
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-04 08:39:40.255509
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-11-05 08:43:15.198610
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-06 08:41:27.473004
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-07 08:40:51.851732
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-08 08:40:29.709668
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-09 08:40:14.386873
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-10 08:40:40.484850
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-11 08:39:55.584660
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-12 08:43:43.796194
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-11-13 08:42:07.471671
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-11-14 08:40:39.492726
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-15 08:41:33.848002
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-11-16 08:42:16.212659
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-17 08:42:10.014781
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-18 08:41:16.634881
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-19 08:45:10.329044
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-11-20 08:42:40.130831
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-11-21 08:42:55.034623
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-22 08:43:49.667676
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-11-23 08:42:02.914396
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-24 08:40:51.897776
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-25 08:40:08.253201
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-26 08:44:42.674722
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-27 08:42:31.382916
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-28 08:42:42.391782
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-11-29 08:42:31.056649
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-11-30 08:42:12.373786
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-12-01 08:46:37.597864
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-12-02 08:41:01.059977
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-03 08:44:49.783216
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-04 08:42:57.262863
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-12-05 08:42:59.072800
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-06 08:42:52.746203
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-07 08:42:21.414439
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-12-08 08:42:50.828268
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-09 08:41:19.424676
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-10 08:45:47.843496
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-11 08:43:09.054726
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-12 08:42:52.735409
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-13 08:42:25.769675
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-14 08:41:51.401467
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-12-15 08:43:00.759823
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-16 08:41:43.664527
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-17 08:45:59.844790
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-18 08:43:29.616379
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-19 08:42:26.019477
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-20 08:34:48.163260
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-21 08:41:43.423403
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-12-22 08:41:16.781169
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-23 08:40:00.903982
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-24 08:44:40.121799
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-25 08:42:41.530025
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-26 08:40:35.196597
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-27 08:40:39.039768
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-28 08:40:24.182122
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-29 08:34:16.505666
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-30 08:40:45.187520
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-12-31 08:45:19.809459
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-01 08:46:40.980405
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-02 08:41:13.804693
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-03 08:42:05.571908
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-04 08:42:19.429047
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-05 08:42:28.087234
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-06 08:41:48.746300
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-07 08:46:52.640863
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-08 08:43:45.485517
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-09 08:43:10.300976
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2024-01-10 08:43:05.300071
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.1/x64/lib/python3.12/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

