2023-07-06 08:59:57.504207
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-08 08:58:14.485244
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-09 09:02:13.023131
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-10 08:58:23.218663
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-02 08:46:51.280175
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-03 08:46:40.990733
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-04 08:46:54.274172
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-05 08:44:52.829113
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-06 08:42:20.410089
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-07 08:46:32.046625
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-08 08:45:23.248673
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-09 08:46:39.916692
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-12 08:36:32.143485
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-13 08:39:44.913390
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-14 08:38:32.448424
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-15 08:37:43.847400
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

