2023-07-06 08:59:57.504207
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-08 08:58:14.485244
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-09 09:02:13.023131
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-07-10 08:58:23.218663
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-02 08:46:51.280175
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-03 08:46:40.990733
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-04 08:46:54.274172
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-05 08:44:52.829113
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-06 08:42:20.410089
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-07 08:46:32.046625
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-08 08:45:23.248673
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-09 08:46:39.916692
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 13, in <module>
    get_all_mooncell()
  File "/home/runner/work/fgo_data/fgo_data/fgo_fetch_all.py", line 9, in get_all_mooncell
    get_all_svt()
  File "/home/runner/work/fgo_data/fgo_data/get/get_all_svt.py", line 16, in get_all_svt
    data = re.search(rule, raw_data).group(0)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

2023-08-12 08:36:32.143485
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-13 08:39:44.913390
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-14 08:38:32.448424
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-15 08:37:43.847400
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-16 08:37:49.084060
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-17 08:37:03.422668
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-18 08:37:31.631737
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-19 08:36:02.741304
list index out of range
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 35, in update_lib
    data = lib_cft(each_cft)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_cft.py", line 69, in lib_cft
    single_cft_detail[each_cd] = info[detail_counter]
                                 ~~~~^^^^^^^^^^^^^^^^
IndexError: list index out of range

2023-08-20 08:39:43.850477
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-08-21 08:38:08.362494
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-08-22 08:38:30.066168
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-23 08:37:47.608576
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-24 08:37:41.396510
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-25 08:38:34.700677
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-26 08:36:59.899399
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-27 08:40:41.236712
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-28 08:39:16.329676
'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 624, in get_pickup
    img_urls = img_soup.get("srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 626, in get_pickup
    img_urls = img_soup.get("data-srcset").split(",")[-1].strip()
               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

2023-08-29 08:38:46.764454
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-08-31 08:38:57.951624
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-01 08:41:37.734541
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-02 08:37:11.698706
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-03 08:41:01.852636
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-04 08:39:44.447683
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-05 08:38:10.814144
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-06 08:38:50.207669
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-07 08:38:17.834586
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.4/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-08 08:38:31.353891
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-09 08:37:46.696093
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-10 08:41:16.371111
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-11 08:39:26.805152
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-12 08:37:46.484138
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-13 08:39:11.394596
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-14 08:38:46.127441
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-15 08:39:21.237719
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-16 08:38:11.961455
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-17 08:41:48.727050
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-18 08:39:34.306467
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-19 08:39:37.314899
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-20 08:39:11.809180
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-21 08:39:19.092392
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-22 08:39:29.570126
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-23 08:37:57.245887
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-24 08:41:39.579797
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-25 08:39:54.427485
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-09-26 08:39:54.234786
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-27 08:40:01.876231
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-09-28 08:39:30.011864
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-09-29 08:39:42.664699
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-09-30 08:38:30.951837
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-01 08:45:17.561806
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-02 08:40:08.341269
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-03 08:40:11.545031
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-04 08:40:16.933262
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-05 08:39:43.483671
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-06 08:39:40.424601
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-07 08:39:17.513421
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-08 08:42:48.771881
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-09 08:40:00.012192
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-10 08:39:31.913808
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-11 08:39:33.430350
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-12 08:38:01.858798
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-13 08:40:46.773198
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-14 08:38:36.396117
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-15 08:42:59.724219
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-16 08:40:56.845462
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-17 08:40:04.065750
object of type 'ReadTimeout' has no len()
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 68, in lib_svt
    get_pickup(svt, soup, url)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 636, in get_pickup
    time_soup = BeautifulSoup(get_content(f"https://fgo.wiki{href}"), 'html.parser')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'ReadTimeout' has no len()

2023-10-18 08:39:57.177593
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.5/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

2023-10-19 08:39:43.235859
'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 433, in get_skills
    title = each_skill_list[0].findParent("div")["title"]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.6/x64/lib/python3.11/site-packages/bs4/element.py", line 1573, in __getitem__
    return self.attrs[key]
           ~~~~~~~~~~^^^^^
KeyError: 'title'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/fgo_data/fgo_data/./__init__.py", line 21, in <module>
    update_lib()
  File "/home/runner/work/fgo_data/fgo_data/fgo_lib.py", line 18, in update_lib
    data = lib_svt(each_svt)
           ^^^^^^^^^^^^^^^^^
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 78, in lib_svt
    get_skills(svt, base, raw_html)
  File "/home/runner/work/fgo_data/fgo_data/lib_online/lib_svt.py", line 444, in get_skills
    skills[each_skill_list[0].find_previous("b").text] = [
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

